// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: echo/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code    uint32                 `protobuf:"varint,1,opt,name=code,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *Error) SetCode(v uint32) {
	x.xxx_hidden_Code = v
}

func (x *Error) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type Error_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Code    uint32
	Message string
}

func (b0 Error_builder) Build() *Error {
	m0 := &Error{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Code = b.Code
	x.xxx_hidden_Message = b.Message
	return m0
}

type Echo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Error       *Error                 `protobuf:"bytes,1,opt,name=error,proto3"`
	xxx_hidden_Message     string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	xxx_hidden_Sequence    uint64                 `protobuf:"varint,3,opt,name=sequence,proto3"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_echo_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_echo_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Echo) GetError() *Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *Echo) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *Echo) GetSequence() uint64 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *Echo) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Echo) SetError(v *Error) {
	x.xxx_hidden_Error = v
}

func (x *Echo) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *Echo) SetSequence(v uint64) {
	x.xxx_hidden_Sequence = v
}

func (x *Echo) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Echo) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *Echo) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Echo) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *Echo) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Echo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Error       *Error
	Message     string
	Sequence    uint64
	DateCreated *timestamppb.Timestamp
}

func (b0 Echo_builder) Build() *Echo {
	m0 := &Echo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_Sequence = b.Sequence
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_echo_echo_proto protoreflect.FileDescriptor

const file_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x0fecho/echo.proto\x12\x04echo\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9e\x01\n" +
	"\x04Echo\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\v.echo.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated2\xb4\x01\n" +
	"\vEchoService\x12!\n" +
	"\x05Unary\x12\n" +
	".echo.Echo\x1a\n" +
	".echo.Echo\"\x00\x12*\n" +
	"\fClientStream\x12\n" +
	".echo.Echo\x1a\n" +
	".echo.Echo\"\x00(\x01\x12*\n" +
	"\fServerStream\x12\n" +
	".echo.Echo\x1a\n" +
	".echo.Echo\"\x000\x01\x12*\n" +
	"\n" +
	"BidiStream\x12\n" +
	".echo.Echo\x1a\n" +
	".echo.Echo\"\x00(\x010\x01B-Z+github.com/lesomnus/grpc-wasm/internal/echob\x06proto3"

var file_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_echo_proto_goTypes = []any{
	(*Error)(nil),                 // 0: echo.Error
	(*Echo)(nil),                  // 1: echo.Echo
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_echo_echo_proto_depIdxs = []int32{
	0, // 0: echo.Echo.error:type_name -> echo.Error
	2, // 1: echo.Echo.date_created:type_name -> google.protobuf.Timestamp
	1, // 2: echo.EchoService.Unary:input_type -> echo.Echo
	1, // 3: echo.EchoService.ClientStream:input_type -> echo.Echo
	1, // 4: echo.EchoService.ServerStream:input_type -> echo.Echo
	1, // 5: echo.EchoService.BidiStream:input_type -> echo.Echo
	1, // 6: echo.EchoService.Unary:output_type -> echo.Echo
	1, // 7: echo.EchoService.ClientStream:output_type -> echo.Echo
	1, // 8: echo.EchoService.ServerStream:output_type -> echo.Echo
	1, // 9: echo.EchoService.BidiStream:output_type -> echo.Echo
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_echo_echo_proto_init() }
func file_echo_echo_proto_init() {
	if File_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_echo_proto_rawDesc), len(file_echo_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_echo_proto_goTypes,
		DependencyIndexes: file_echo_echo_proto_depIdxs,
		MessageInfos:      file_echo_echo_proto_msgTypes,
	}.Build()
	File_echo_echo_proto = out.File
	file_echo_echo_proto_goTypes = nil
	file_echo_echo_proto_depIdxs = nil
}
