// @generated by protobuf-ts 2.10.0 with parameter server_generic
// @generated from protobuf file "echo/echo.proto" (package "echo", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message echo.Echo
 */
export interface Echo {
    /**
     * Server should response with this status.
     *
     * @generated from protobuf field: echo.Status status = 1;
     */
    status?: Status;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: uint64 sequence = 3;
     */
    sequence: bigint;
    /**
     * Perform a circular shift on themessage
     * to the right by the given number.
     * If the number is negative, shift to the left.
     *
     * @generated from protobuf field: int64 circular_shift = 4;
     */
    circularShift: bigint;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp date_created = 15;
     */
    dateCreated?: Timestamp;
}
/**
 * @generated from protobuf message echo.Status
 */
export interface Status {
    /**
     * @generated from protobuf field: int32 code = 1;
     */
    code: number;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Echo$Type extends MessageType<Echo> {
    constructor() {
        super("echo.Echo", [
            { no: 1, name: "status", kind: "message", T: () => Status },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "circular_shift", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 15, name: "date_created", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Echo>): Echo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.sequence = 0n;
        message.circularShift = 0n;
        if (value !== undefined)
            reflectionMergePartial<Echo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Echo): Echo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* echo.Status status */ 1:
                    message.status = Status.internalBinaryRead(reader, reader.uint32(), options, message.status);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* uint64 sequence */ 3:
                    message.sequence = reader.uint64().toBigInt();
                    break;
                case /* int64 circular_shift */ 4:
                    message.circularShift = reader.int64().toBigInt();
                    break;
                case /* google.protobuf.Timestamp date_created */ 15:
                    message.dateCreated = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.dateCreated);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Echo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* echo.Status status = 1; */
        if (message.status)
            Status.internalBinaryWrite(message.status, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* uint64 sequence = 3; */
        if (message.sequence !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.sequence);
        /* int64 circular_shift = 4; */
        if (message.circularShift !== 0n)
            writer.tag(4, WireType.Varint).int64(message.circularShift);
        /* google.protobuf.Timestamp date_created = 15; */
        if (message.dateCreated)
            Timestamp.internalBinaryWrite(message.dateCreated, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message echo.Echo
 */
export const Echo = new Echo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Status$Type extends MessageType<Status> {
    constructor() {
        super("echo.Status", [
            { no: 1, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Status>): Status {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = 0;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<Status>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Status): Status {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 code */ 1:
                    message.code = reader.int32();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Status, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 code = 1; */
        if (message.code !== 0)
            writer.tag(1, WireType.Varint).int32(message.code);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message echo.Status
 */
export const Status = new Status$Type();
/**
 * @generated ServiceType for protobuf service echo.EchoService
 */
export const EchoService = new ServiceType("echo.EchoService", [
    { name: "Unary", options: {}, I: Echo, O: Echo },
    { name: "ClientStream", clientStreaming: true, options: {}, I: Echo, O: Echo },
    { name: "ServerStream", serverStreaming: true, options: {}, I: Echo, O: Echo },
    { name: "BidiStream", serverStreaming: true, clientStreaming: true, options: {}, I: Echo, O: Echo }
]);
