// @generated by protobuf-ts 2.10.0 with parameter server_generic
// @generated from protobuf file "echo/echo.proto" (package "echo", syntax proto3)
// tslint:disable
import { RpcOutputStream } from "@protobuf-ts/runtime-rpc";
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { EchoResponse } from "./echo";
import { EchoRequest } from "./echo";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service echo.EchoService
 */
export interface IEchoService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: Once(echo.EchoRequest) returns (echo.EchoResponse);
     */
    once(request: EchoRequest, context: T): Promise<EchoResponse>;
    /**
     * @generated from protobuf rpc: Many(echo.EchoRequest) returns (stream echo.EchoResponse);
     */
    many(request: EchoRequest, responses: RpcInputStream<EchoResponse>, context: T): Promise<void>;
    /**
     * @generated from protobuf rpc: Buff(stream echo.EchoRequest) returns (echo.EchoResponse);
     */
    buff(requests: RpcOutputStream<EchoRequest>, context: T): Promise<EchoResponse>;
    /**
     * @generated from protobuf rpc: Live(stream echo.EchoRequest) returns (stream echo.EchoResponse);
     */
    live(requests: RpcOutputStream<EchoRequest>, responses: RpcInputStream<EchoResponse>, context: T): Promise<void>;
}
