// @generated by protobuf-ts 2.10.0 with parameter server_generic
// @generated from protobuf file "echo/echo.proto" (package "echo", syntax proto3)
// tslint:disable
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { RpcOutputStream } from "@protobuf-ts/runtime-rpc";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
import { Echo } from "./echo";
/**
 * @generated from protobuf service echo.EchoService
 */
export interface IEchoService<T = ServerCallContext> {
	/**
	 * @generated from protobuf rpc: Unary(echo.Echo) returns (echo.Echo);
	 */
	unary(request: Echo, context: T): Promise<Echo>;
	/**
	 * @generated from protobuf rpc: ClientStream(stream echo.Echo) returns (echo.Echo);
	 */
	clientStream(requests: RpcOutputStream<Echo>, context: T): Promise<Echo>;
	/**
	 * @generated from protobuf rpc: ServerStream(echo.Echo) returns (stream echo.Echo);
	 */
	serverStream(
		request: Echo,
		responses: RpcInputStream<Echo>,
		context: T,
	): Promise<void>;
	/**
	 * @generated from protobuf rpc: BidiStream(stream echo.Echo) returns (stream echo.Echo);
	 */
	bidiStream(
		requests: RpcOutputStream<Echo>,
		responses: RpcInputStream<Echo>,
		context: T,
	): Promise<void>;
}
